#!/bin/bash 
#
# Simple powerfull bash template engine to parse bash from text 
#
 
fetch(){
  IFS=''; cat - | sed 's/\\/\\\\\\\\/g' | while read -r line; do 
    [[ "$line" =~ '$' ]] && line="$(eval "echo \"$( echo "$line" | sed 's/"/\\"/g')\"")"; 
    echo "$line"
  done
}

f="$(<$1)"; echo "$f" | fetch > "$1"
