#!/bin/bash
find src -name "*.coffee" | grep -v node_modules | while read file; do
  echo "compiling ${file/coffee$/js/g}";
  slug="$(dirname "$file")" ; outdir="${slug/src/lib}"
  coffee -o "$outdir" -c -b --no-header "$file" ; 
  [[ ! -n $NOCOMMIT ]] && git add "${file/coffee$/js/}";
done
coffee -c -b --no-header test/test.coffee
git add test/test.js

# generate docs
[[ ! -d doc ]] && mkdir doc 
.hooks/markdox lib/model.js -o doc/model.js.md 
.hooks/markdox lib/user.js  -o doc/user.js.md 
.hooks/bashdown doc/model.js.md

# document the undocumented
#smartcomments -g -c .smartcomments.json

