#!/bin/bash
find src -name "*.coffee" | grep -v node_modules | while read file; do
  echo "compiling ${file/coffee$/js/g}";
  slug="$(dirname "$file")" ; outdir="${slug/src/lib}"
  coffee -o "$outdir" -c -b --no-header "$file" ; git add "${file/coffee$/js/}";
done

# document the undocumented
smartcomments -g -c .smartcomments.json

# generate docs
[[ ! -d doc ]] && mkdir doc 
node_modules/.bin/markdox lib/model.js -o doc/model.js.md 
node_modules/.bin/markdox lib/user.js  -o doc/user.js.md 
.hooks/bashdown doc/model.js.md
